//! Platform-independent input: raw events collected by the platform layer
//! ([`RawInput`]) and the per-frame state derived from them ([`InputState`]).

use crate::{Point, Rect, Vec2};

/// Points scrolled by one notch of a mouse wheel ([`Event::Scroll`] of a
/// wheel that reports "lines" is converted with this factor).
pub const POINTS_PER_SCROLL_LINE: f32 = 50.0;

/// A mouse (or touchpad) button.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PointerButton {
    /// Usually the left button.
    Primary,
    /// Usually the right button.
    Secondary,
    /// Usually the middle button or wheel click.
    Middle,
}

impl PointerButton {
    const COUNT: usize = 3;

    const fn index(self) -> usize {
        match self {
            Self::Primary => 0,
            Self::Secondary => 1,
            Self::Middle => 2,
        }
    }
}

/// Keys the library reacts to. Text input arrives separately as
/// [`Event::Text`].
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Key {
    /// Tab: moves keyboard focus.
    Tab,
    /// Enter / Return.
    Enter,
    /// The space bar.
    Space,
    /// Escape.
    Escape,
    /// Backspace: deletes before the cursor.
    Backspace,
    /// Delete: deletes after the cursor.
    Delete,
    /// Left arrow.
    ArrowLeft,
    /// Right arrow.
    ArrowRight,
    /// Up arrow.
    ArrowUp,
    /// Down arrow.
    ArrowDown,
    /// Home.
    Home,
    /// End.
    End,
    /// Page Up.
    PageUp,
    /// Page Down.
    PageDown,
    // Letters used by shortcuts (typed text arrives as `Event::Text`).
    /// The A key (select all with Cmd/Ctrl).
    A,
    /// The C key (copy with Cmd/Ctrl).
    C,
    /// The V key (paste with Cmd/Ctrl).
    V,
    /// The X key (cut with Cmd/Ctrl).
    X,
    /// The Y key (redo on some platforms).
    Y,
    /// The Z key (undo with Cmd/Ctrl).
    Z,
}

/// Modifier keys held during an event.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct Modifiers {
    /// Shift is held.
    pub shift: bool,
    /// Control is held.
    pub ctrl: bool,
    /// Alt (Option on macOS) is held.
    pub alt: bool,
    /// The Command key on macOS, the Windows/Super key elsewhere.
    pub logo: bool,
}

impl Modifiers {
    /// No modifier held.
    pub const NONE: Self = Self {
        shift: false,
        ctrl: false,
        alt: false,
        logo: false,
    };

    /// Only Shift held.
    pub const SHIFT: Self = Self {
        shift: true,
        ..Self::NONE
    };

    /// The platform's shortcut modifier: Command on macOS, Ctrl elsewhere.
    pub fn command(&self) -> bool {
        if cfg!(target_os = "macos") {
            self.logo
        } else {
            self.ctrl
        }
    }

    /// Only the shortcut modifier (see [`Modifiers::command`]) is held.
    pub fn command_only(&self) -> bool {
        let other = if cfg!(target_os = "macos") {
            self.ctrl
        } else {
            self.logo
        };
        self.command() && !self.shift && !self.alt && !other
    }

    /// True if no modifier is held.
    pub fn is_none(&self) -> bool {
        *self == Self::NONE
    }
}

/// Something that happened since the previous frame. Positions are in
/// logical points.
#[derive(Clone, Debug, PartialEq)]
pub enum Event {
    /// The pointer moved to this position.
    PointerMoved(Point),
    /// A pointer button was pressed or released.
    PointerButton {
        /// Where the pointer was.
        pos: Point,
        /// Which button.
        button: PointerButton,
        /// `true` when pressed, `false` when released.
        pressed: bool,
        /// Modifiers held at the time.
        modifiers: Modifiers,
    },
    /// The pointer left the window.
    PointerGone,
    /// Scrolling, in points. Positive `y` scrolls content down (wheel up).
    Scroll(Vec2),
    /// A key was pressed or released.
    Key {
        /// Which key.
        key: Key,
        /// `true` when pressed, `false` when released.
        pressed: bool,
        /// Generated by holding the key down (auto-repeat).
        repeat: bool,
        /// Modifiers held at the time.
        modifiers: Modifiers,
    },
    /// Text typed by the user (already composed by the OS).
    Text(String),
    /// The window gained (`true`) or lost (`false`) keyboard focus.
    WindowFocused(bool),
    /// The user asked to copy the selection (Cmd/Ctrl+C).
    Copy,
    /// The user asked to cut the selection (Cmd/Ctrl+X).
    Cut,
    /// The user pasted this text (Cmd/Ctrl+V).
    Paste(String),
    /// Input method (IME) composition, for accented and Asian text.
    Ime(ImeEvent),
}

/// Input method (IME) events: while composing, the text in progress is
/// shown at the cursor ("preedit") and replaced by the final text on commit.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ImeEvent {
    /// The input method was turned on.
    Enabled,
    /// Text being composed, not yet part of the document. Empty when the
    /// composition was cancelled.
    Preedit(String),
    /// Final text to insert.
    Commit(String),
    /// The input method was turned off.
    Disabled,
}

/// Everything the platform layer collected for one frame.
#[derive(Clone, Debug, PartialEq)]
pub struct RawInput {
    /// Seconds since the app started.
    pub time: f64,
    /// The window's drawable area, in logical points.
    pub screen_rect: Rect,
    /// Physical pixels per logical point.
    pub pixels_per_point: f32,
    /// Events in the order they happened.
    pub events: Vec<Event>,
}

impl Default for RawInput {
    fn default() -> Self {
        Self {
            time: 0.0,
            screen_rect: Rect::from_min_size(Point::ZERO, Vec2::new(800.0, 600.0)),
            pixels_per_point: 1.0,
            events: Vec::new(),
        }
    }
}

/// Pointer (mouse) state for the current frame.
#[derive(Clone, Debug, Default)]
pub struct PointerState {
    /// Latest position, `None` if the pointer is outside the window.
    pos: Option<Point>,
    /// Movement since last frame.
    delta: Vec2,
    down: [bool; PointerButton::COUNT],
    /// Where each button was pressed this frame, if it was.
    pressed_at: [Option<Point>; PointerButton::COUNT],
    /// Where each button was released this frame, if it was.
    released_at: [Option<Point>; PointerButton::COUNT],
    /// Where the current (or last) press of the primary button started.
    press_origin: Option<Point>,
}

impl PointerState {
    /// Latest pointer position, if the pointer is over the window.
    pub fn pos(&self) -> Option<Point> {
        self.pos
    }

    /// Pointer movement since the previous frame.
    pub fn delta(&self) -> Vec2 {
        self.delta
    }

    /// True while `button` is held down.
    pub fn is_down(&self, button: PointerButton) -> bool {
        self.down[button.index()]
    }

    /// Where `button` was pressed during this frame, if it was.
    pub fn pressed_at(&self, button: PointerButton) -> Option<Point> {
        self.pressed_at[button.index()]
    }

    /// Where `button` was released during this frame, if it was.
    pub fn released_at(&self, button: PointerButton) -> Option<Point> {
        self.released_at[button.index()]
    }

    /// The primary button was pressed this frame.
    pub fn primary_pressed(&self) -> bool {
        self.pressed_at(PointerButton::Primary).is_some()
    }

    /// The primary button was released this frame.
    pub fn primary_released(&self) -> bool {
        self.released_at(PointerButton::Primary).is_some()
    }

    /// The primary button is held down.
    pub fn primary_down(&self) -> bool {
        self.is_down(PointerButton::Primary)
    }

    /// Where the latest primary press started (kept while dragging).
    pub fn press_origin(&self) -> Option<Point> {
        self.press_origin
    }

    /// The position that matters for hit testing this frame: where the
    /// primary button was pressed if it was, otherwise the latest position.
    pub fn interact_pos(&self) -> Option<Point> {
        self.pressed_at(PointerButton::Primary).or(self.pos)
    }
}

/// Input for one frame, derived from [`RawInput`] and the previous state.
#[derive(Clone, Debug)]
pub struct InputState {
    /// Mouse state.
    pub pointer: PointerState,
    /// Seconds since the app started.
    pub time: f64,
    /// Seconds since the previous frame.
    pub dt: f32,
    /// The window's drawable area, in logical points.
    pub screen_rect: Rect,
    /// Physical pixels per logical point.
    pub pixels_per_point: f32,
    /// Modifiers currently held.
    pub modifiers: Modifiers,
    /// Total scroll this frame, in points.
    pub scroll_delta: Vec2,
    /// The window has keyboard focus.
    pub window_focused: bool,
    /// Key presses this frame (including auto-repeat), in order.
    keys_pressed: Vec<(Key, Modifiers)>,
    /// All raw events of this frame, e.g. for text input.
    pub events: Vec<Event>,
}

impl Default for InputState {
    fn default() -> Self {
        let raw = RawInput::default();
        Self {
            pointer: PointerState::default(),
            time: raw.time,
            dt: 0.0,
            screen_rect: raw.screen_rect,
            pixels_per_point: raw.pixels_per_point,
            modifiers: Modifiers::NONE,
            scroll_delta: Vec2::ZERO,
            window_focused: true,
            keys_pressed: Vec::new(),
            events: Vec::new(),
        }
    }
}

impl InputState {
    /// Advances to a new frame: applies `raw` on top of the previous state
    /// (buttons held down stay down, position is kept, ...).
    pub fn begin_frame(&mut self, raw: RawInput) {
        let pointer = &mut self.pointer;
        let previous_pos = pointer.pos;
        pointer.pressed_at = [None; PointerButton::COUNT];
        pointer.released_at = [None; PointerButton::COUNT];
        self.keys_pressed.clear();
        self.scroll_delta = Vec2::ZERO;

        for event in &raw.events {
            match event {
                Event::PointerMoved(pos) => pointer.pos = Some(*pos),
                Event::PointerGone => pointer.pos = None,
                Event::PointerButton {
                    pos,
                    button,
                    pressed,
                    modifiers,
                } => {
                    let i = button.index();
                    pointer.pos = Some(*pos);
                    pointer.down[i] = *pressed;
                    self.modifiers = *modifiers;
                    if *pressed {
                        pointer.pressed_at[i] = Some(*pos);
                        if *button == PointerButton::Primary {
                            pointer.press_origin = Some(*pos);
                        }
                    } else {
                        pointer.released_at[i] = Some(*pos);
                    }
                }
                Event::Scroll(delta) => self.scroll_delta += *delta,
                Event::Key {
                    key,
                    pressed,
                    modifiers,
                    ..
                } => {
                    self.modifiers = *modifiers;
                    if *pressed {
                        self.keys_pressed.push((*key, *modifiers));
                    }
                }
                Event::Text(_) | Event::Copy | Event::Cut | Event::Paste(_) | Event::Ime(_) => {}
                Event::WindowFocused(focused) => {
                    self.window_focused = *focused;
                    if !focused {
                        // Releases may be lost while unfocused.
                        pointer.down = [false; PointerButton::COUNT];
                    }
                }
            }
        }
        pointer.delta = match (previous_pos, pointer.pos) {
            (Some(a), Some(b)) => b - a,
            _ => Vec2::ZERO,
        };

        // Clamp to avoid huge jumps after the app was idle for a while.
        self.dt = ((raw.time - self.time) as f32).clamp(0.0, 0.1);
        self.time = raw.time;
        self.screen_rect = raw.screen_rect;
        self.pixels_per_point = raw.pixels_per_point;
        self.events = raw.events;
    }

    /// Takes this frame's scrolling, leaving none for widgets handled later
    /// (e.g. a 3D view inside a [scroll area] keeps the wheel for zooming).
    ///
    /// [scroll area]: https://docs.rs/rustroke/latest/rustroke/struct.ScrollArea.html
    pub fn consume_scroll(&mut self) -> Vec2 {
        std::mem::replace(&mut self.scroll_delta, Vec2::ZERO)
    }

    /// True if `key` was pressed this frame, with any modifiers.
    pub fn key_pressed(&self, key: Key) -> bool {
        self.keys_pressed.iter().any(|(k, _)| *k == key)
    }

    /// Removes one press of `key` with exactly `modifiers` and returns
    /// whether there was one. Lets a widget claim a key so others ignore it.
    pub fn consume_key(&mut self, key: Key, modifiers: Modifiers) -> bool {
        if let Some(i) = self
            .keys_pressed
            .iter()
            .position(|(k, m)| *k == key && *m == modifiers)
        {
            self.keys_pressed.remove(i);
            true
        } else {
            false
        }
    }

    /// Number of presses of `key` this frame (auto-repeat counts).
    pub fn key_presses(&self, key: Key) -> usize {
        self.keys_pressed.iter().filter(|(k, _)| *k == key).count()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::point;

    fn press(pos: Point, pressed: bool) -> Event {
        Event::PointerButton {
            pos,
            button: PointerButton::Primary,
            pressed,
            modifiers: Modifiers::NONE,
        }
    }

    fn frame(input: &mut InputState, time: f64, events: Vec<Event>) {
        input.begin_frame(RawInput {
            time,
            events,
            ..Default::default()
        });
    }

    #[test]
    fn press_and_release_are_per_frame_but_down_persists() {
        let mut input = InputState::default();
        frame(&mut input, 0.0, vec![press(point(5.0, 5.0), true)]);
        assert!(input.pointer.primary_pressed());
        assert!(input.pointer.primary_down());

        frame(&mut input, 0.1, vec![Event::PointerMoved(point(8.0, 9.0))]);
        assert!(!input.pointer.primary_pressed());
        assert!(input.pointer.primary_down());
        assert_eq!(input.pointer.delta(), Vec2::new(3.0, 4.0));
        assert_eq!(input.pointer.press_origin(), Some(point(5.0, 5.0)));

        frame(&mut input, 0.2, vec![press(point(8.0, 9.0), false)]);
        assert!(input.pointer.primary_released());
        assert!(!input.pointer.primary_down());
    }

    #[test]
    fn click_within_one_frame_is_seen() {
        let mut input = InputState::default();
        let p = point(1.0, 1.0);
        frame(&mut input, 0.0, vec![press(p, true), press(p, false)]);
        assert!(input.pointer.primary_pressed());
        assert!(input.pointer.primary_released());
        assert!(!input.pointer.primary_down());
        assert_eq!(input.pointer.interact_pos(), Some(p));
    }

    #[test]
    fn keys_can_be_consumed() {
        let mut input = InputState::default();
        let tab = |modifiers| Event::Key {
            key: Key::Tab,
            pressed: true,
            repeat: false,
            modifiers,
        };
        frame(
            &mut input,
            0.0,
            vec![tab(Modifiers::NONE), tab(Modifiers::SHIFT)],
        );
        assert_eq!(input.key_presses(Key::Tab), 2);
        assert!(input.consume_key(Key::Tab, Modifiers::SHIFT));
        assert!(!input.consume_key(Key::Tab, Modifiers::SHIFT));
        assert!(input.key_pressed(Key::Tab));
    }

    #[test]
    fn losing_window_focus_releases_buttons() {
        let mut input = InputState::default();
        frame(&mut input, 0.0, vec![press(point(0.0, 0.0), true)]);
        frame(&mut input, 0.1, vec![Event::WindowFocused(false)]);
        assert!(!input.pointer.primary_down());
    }

    #[test]
    fn dt_is_clamped() {
        let mut input = InputState::default();
        frame(&mut input, 0.0, vec![]);
        frame(&mut input, 5.0, vec![]);
        assert_eq!(input.dt, 0.1);
    }
}
