[package]
name = "rustroke-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
description = "wgpu renderer for tessellated meshes, on screen or offscreen."

[lints]
workspace = true

[dependencies]
wgpu.workspace = true
log.workspace = true
rustroke-core.workspace = true
bytemuck.workspace = true

[dev-dependencies]
png.workspace = true
rustroke-text.workspace = true
rustroke-widgets.workspace = true
pollster.workspace = true
